# biocypher module settings
biocypher:

  offline: true

neo4j:

  database_name: neo4j
  wipe: true
  delimiter: '\t'
  array_delimiter: '|'
  quote_character: "'"
  skip_duplicate_nodes: true
  skip_bad_relationships: true