Title: BioCypher graph schema configuration file for CROssBAR v2

# This configuration file establishes the hierarchy and connectivity in a newly
# set-up BioCypher property graph database. Naming should adhere to Biolink
# nomenclature (available at https://biolink.github.io/biolink-model/ or via 
# the python module 'biolink-model-toolkit').

# The BioCypher YAML file specifies only the leaves of the hierarchy tree of
# the desired graph; the hierarchical structure of entities will be derived 
# from the Biolink model. Thus, only the immediate constituents of the graph
# need to be specified in the schema config.


# ---
# "Named Things"
# ---
# The implementation of named things is fairly straightforward, since they are
# usually represented in node form, which is also the Biolink recommendation.
# The same is not true for associations.
#
# A little more complex is the representation of aggregates of named things, 
# for instance in the case of functional protein complexes. These are represented
# by so-called "mixins", which are not officially part of the hierarchy.

# Protein: # this is the Biolink entity name and will be used as the node label
         #do not modify or else the Biolink translation will fail
  # represented_as: node
  # preferred_id: UniProtKB # this is the Biolink spelling of the identifier used
  #it represents a CURIE URI prefix
  # label_in_input: protein # modify this to allow translation
  # this is the entity name (ie, type) in the input database
  

gene:
  represented_as: node
  preferred_id: ncbigene
  label_in_input: gene
  properties:    
    genes: str[]
    kegg: str[]
    ensembl: str[]
    ensembl_gene_ids: str[]

protein:
  represented_as: node
  preferred_id: uniprot
  label_in_input: protein
  properties:
    secondary_ids: str[]
    length: int
    mass: int
    protein_names: str[]
    proteome: str[]
    organism_id: int
    ec: str[]
    virus_hosts: int[] 
  
organism taxon:
  represented_as: node
  preferred_id: ncbitaxon
  label_in_input: organism
  properties:
    organism: str
  
# disease:
  # represented_as: node
  # preferred_id: mondo
  # label_in_input: Disease

# pathway:
  # represented_as: node
  # preferred_id: [reactome, kegg]
  # label_in_input: [Pathway_Reactome, Pathway_KEGG]

# small molecule:  # drug has only RXCUI, NDC, UMLS identifiers
  # represented_as: node
  # preferred_id: drugbank
  # label_in_input: Drug
  
# molecular mixture: # there is no compound in Biolink. could be molecular mixture
  # represented_as: node
  # preferred_id: chembl.compound
  # label_in_input: Compound

# Cell: # relevant?
  # represented_as: node
  # preferred_id: CL
  # label_in_input: Cell

# phenotype:
  # represented_as: node
  # preferred_id: hp
  # label_in_input: Phenotype
      
# biological process: # other two go categories?
  # represented_as: node
  # preferred_id: go
  # label_in_input: Function

# cell line:
  # represented_as: node
  # preferred_id: ccle
  # label_in_input: Cell_Line

# tissue:
  # is_a: grossanatomicalstructure
  # represented_as: node
  # preferred_id: uberon
  # label_in_input: Tissue

# patient:
  # is_a: case
  # represented_as: node
  # preferred_id: id
  # label_in_input: Patient
  
# protein domain:
  # represented_as: node
  # preferred_id: interpro
  # label_in_input: Domain

# side effect:
  # is_a: phenotypic feature
  # represented_as: node
  # preferred_id: sider.effect
  # label_in_input: Side_Effect

# location:
  # represented_as: node
  # preferred_id: go
  # label_in_input: Location

# ---
# Associations
# ---
# Associations are not supposed to be represented in node form as per the 
# specifications of Biolink. However, in an analytic context, it often makes 
# sense to represent interactions as nodes in Neo4j, because it enables, for
# instance, the annotation of a relationship with a publication as source of
# evidence (also known as reification in the knowledge graph world). 

# The Biolink specifications for these types of relationships do 
# not go into depth; for example, the hierarchy for molecular interactions
# (ie, "associations") ends at "PairwiseMolecularInteraction", there are no 
# explicit terms for protein-protein-interaction, phosphorylation, miRNA-
# targeting, etc. Biolink proposes to use interaction identifiers from 
# ontologies, such as https://www.ebi.ac.uk/ols/ontologies/mi/.


gene to protein relationship:
  is_a: gene to gene product relationship
  represented_as: edge
  label_as_edge: Encodes
  preferred_id: id
  source: gene
  target: protein
  label_in_input: Encodes
  
protein to organism taxon association:
  is_a: association
  represented_as: edge
  label_as_edge: Belongs_To
  preferred_id: id
  source: protein
  target: organismTaxon
  label_in_input: Belongs_To  
  
post translational interaction:
  represented_as: edge
  label_as_edge: Interacts_With
  preferred_id: id
  source: protein
  target: protein
  label_in_input: Interacts_With
  properties:    
    source: str[]
    pubmed_id: int[]
    method: str
    interaction_type: str
    intact_score: float
    string_combined_score: int
    string_physical_combined_score: int    
    

# protein to protein domain association:
  # represented_as: edge
  # label_as_edge: Has_Domain
  # preferred_id: id
  # source: protein
  # target: protein domain
  # label_in_input: Protein_Has_Domain

# protein to biological process association:
  # is_a: macromolecular machine to biological process association
  # represented_as: edge
  # label_as_edge: Enables
  # preferred_id: id
  # source: protein
  # target: biological process
  # label_in_input: Enables

# protein to cellular component association:
  # is_a: macromolecular machine to cellular component association
  # represented_as: edge
  # label_as_edge: Localizes_To
  # preferred_id: id
  # source: protein
  # target: cellular component
  # label_in_input: Localizes_To

# protein to pathway association:
  # represented_as: edge
  # label_as_edge: Takes_Part_In
  # preferred_id: id
  # source: protein
  # target: pathway
  # label_in_input: Take_Part_In

# protein to disease association:
  # represented_as: edge
  # label_as_edge: Is_Targeted_In
  # preferred_id: id
  # source: protein
  # target: disease
  # label_in_input: Protein_Is_Related_To_Disease

# gene to gene homology association:
  # represented_as: edge
  # label_as_edge: Is_Ortholog_To
  # preferred_id: id
  # source: gene
  # target: gene
  # label_in_input: Is_Ortholog_To

# pairwise gene to gene interaction:
  # represented_as: edge
  # label_as_edge: Regulates
  # preferred_id: id
  # source: gene
  # target: gene
  # label_in_input: Regulates

# mutation to tissue association:
  # is_a: [genotype to tissue association, association]
  # represented_as: edge
  # label_as_edge: Is_Mutated_In
  # preferred_id: id
  # source: gene
  # target: tissue
  # label_in_input: Gene_Is_Mutated_In_Tissue

# mutation to cell line association:
  # is_a: [genotype to cell line association, association]
  # represented_as: edge
  # label_as_edge: Is_Mutated_In
  # preferred_id: id
  # source: gene
  # target: cell line
  # label_in_input: Gene_Is_Mutated_In_Cell_Line

# expression to tissue association:
  # is_a: [genotype to tissue association, association]
  # represented_as: edge
  # label_as_edge: Is_DEG_In
  # preferred_id: id
  # source: gene
  # target: tissue
  # label_in_input: Gene_Is_DEG_In_Tissue

# expression to cell line association:
  # is_a: [genotype to cell line association, association]
  # represented_as: edge
  # label_as_edge: Is_DEG_In
  # preferred_id: id
  # source: gene
  # target: cell line
# label_in_input: Gene_Is_DEG_In_Cell_Line

# gene to phenotypic feature association:
  # represented_as: edge
  # label_as_edge: Is_Associated_With
  # preferred_id: id
  # source: gene
  # target: phenotypic feature
  # label_in_input: Gene_Is_Associated_With_Phenotype

# mutation to case association:
  # is_a: association
  # represented_as: edge
  # label_as_edge: Is_Mutated_In
  # preferred_id: id
  # source: gene
  # target: case
  # label_in_input: Gene_Is_Mutated_In_Patient

# expression to case association:
  # is_a: association
  # represented_as: edge
  # label_as_edge: Is_DEG_In
  # preferred_id: id
  # source: gene
  # target: case
  # label_in_input: Gene_Is_DEG_In_Patient

# gene to pathway association:
  # represented_as: edge
  # label_as_edge: Is_Member_Of
  # source: protein
  # target: pathway
  # preferred_id: id
  # label_in_input: Is_Member_Of

# gene to disease association:
  # represented_as: edge
  # label_as_edge: Is_Related_To
  # preferred_id: id
  # source: gene
  # target: disease
  # label_in_input: Gene_Is_Related_To_Disease

# drug interaction:
  # is_a: chemical to chemical association
  # represented_as: edge
  # label_as_edge: Interacts_With
  # preferred_id: id
  # source: small molecule
  # target: small molecule
  # label_in_input: Drug_Interacts_With_Drug

# small molecule to protein association:
  # represented_as: edge
  # label_as_edge: Targets
  # preferred_id: id
  # source: small molecule
  # target: protein
  # label_in_input: Drug_Targets_Protein

# small molecule to side effect association:
  # represented_as: edge
  # label_as_edge: Has_Side_Effect
  # preferred_id: id
  # source: small molecule
  # target: side effect
  # label_in_input: Drug_Has_Side_Effect

# small molecule to tissue association:
  # represented_as: edge
  # preferred_id: id
  # source: small molecule
  # target: tissue
  # label_in_input: Drug_Targets_Tissue

# small molecule to cell line association:
  # represented_as: edge
  # preferred_id: id
  # source: small molecule
  # target: tissue
  # label_in_input: Drug_Targets_Cell_Line

# small molecule to pathway association:
  # represented_as: edge
  # label_as_edge: Has_Target_In
  # preferred_id: id
  # source: small molecule
  # target: pathway
  # label_in_input: Has_Target_In

# molecular mixture to protein association:
  # represented_as: edge
  # label_as_edge: Compound_Targets_Protein
  # preferred_id: id
  # source: molecular mixture
  # target: protein
  # label_in_input: Compound_Targets_Protein

# tissue to disease association:
  # represented_as: edge
  # label_as_edge: Has_Disease
  # preferred_id: id
  # source: tissue
  # target: disease
  # label_in_input: Tissue_Has_Disease

# cell line as a model of disease association:
  # represented_as: edge
  # preferred_id: id
  # source: cell line
  # target: disease
  # label_in_input: Cell_Line_Has_Disease

# case to disease association:
  # represented_as: edge
  # label_as_edge: Has_Disease
  # preferred_id: id
  # source: patient
  # target: disease
  # label_in_input: Patient_Has_Disease

# disease to disease association:
  # represented_as: edge
  # label_as_edge: Comorbid_With
  # preferred_id: id
  # source: disease
  # target: disease
  # label_in_input: Comorbid_With

# disease to phenotypic feature association:
  # represented_as: edge
  # label_as_edge: Is_Associated_With
  # preferred_id: id
  # source: disease
  # target: phenotypic feature
  # label_in_input: Disease_Is_Associated_With_Phenotype

# disease to pathway association:
  # represented_as: edge
  # label_as_edge: Modulates
  # preferred_id: id
  # source: disease
  # target: pathway
  # label_in_input: Modulates

# disease to small molecule association:
  # represented_as: edge
  # label_as_edge: Is_Treated_By
  # preferred_id: id
  # source: disease
  # target: small molecule
  # label_in_input: Is_Treated_By

# protein domain to molecular activity association:
  # represented_as: edge
  # label_as_edge: Has_Function
  # preferred_id: id
  # source: protein domain
  # target: molecular activity
  # label_in_input: Domain_Has_Function

# protein domain to cellular component association:
  # represented_as: edge
  # preferred_id: id
  # source: protein domain
  # target: cellular component
  # label_in_input: Domain_Has_Location

# suggestion for drug - small molecule
# drug to small molecule association:
  # is_a: association
  # represented_as: edge
  # label_as_edge: Contains_Active_Ingredient
  # preferred_id: id
  # source: drug
  # target: small molecule
  # label_in_input: Contains_Active_Ingredient
